name: country_list_picker
description: CountryListPicker is flutter package for customizable country selection package with multi-languages support.
version: 1.0.2
homepage: https://github.com/AmremadDev/country-list-picker.git
# publish_to: none

#environment:
#  sdk: '>=2.18.4 <3.0.0'
#  flutter: ">=1.17.0"

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
  fonts:
    - family: Urbanist
      fonts:
          - asset: fonts/Urbanist-Black.ttf
            weight: 900
          - asset: fonts/Urbanist-Bold.ttf
            weight: 700
          - asset: fonts/Urbanist-ExtraBold.ttf
            weight: 800
          - asset: fonts/Urbanist-ExtraLight.ttf
            weight: 200
          - asset: fonts/Urbanist-Light.ttf
            weight: 300
          - asset: fonts/Urbanist-Medium.ttf
            weight: 500
          - asset: fonts/Urbanist-Regular.ttf
            weight: 400
          - asset: fonts/Urbanist-SemiBold.ttf
            weight: 600
          - asset: fonts/Urbanist-Thin.ttf
            weight: 100
 